version: '2'

services:

  jenkins-agent:
    container_name: jenkins-agent
    image: vfarcic/jenkins-swarm-agent
    privileged: true
    environment:
      - COMMAND_OPTIONS=-master ${JENKINS_ADDRESS} -username ${USER} -password ${PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
